name: Publish Helm OSS charts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'charts/**'
      - "!charts/**/Chart.yaml"
  workflow_dispatch:

jobs:
  generate-semantic-version:
    name: Generate semantic version
    runs-on: ubuntu-22.04
    outputs:
      next-version: ${{ steps.ver.outputs.fragment }}
      tag: ${{ steps.sem-ver.outputs.version_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: paulhatch/semantic-version@v4.0.3
        id: sem-ver
        with:
          tag_prefix: "v"
          major_pattern: "feat:"
          minor_pattern: "fix:"
          format: "${major}.${minor}.${patch}"
          change_path: "./charts"
          bump_each_commit: true
          namespace: helm

      - name: "Remove -helm from ver number"
        shell: bash
        env:
          VERSION: ${{ steps.sem-ver.outputs.version }}
        id: ver
        run: echo "::set-output name=fragment::${VERSION%%-*}"

  release-chart:
    name: Chart release
    runs-on: ubuntu-22.04
    needs: ["generate-semantic-version"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "gh_pages"
          path: "./.github/airbyte-oss"

      - name: Replace semantic version in main chart for deps
        shell: bash
        working-directory: ./charts
        run: |
          sed -i -E "s/    version: [[:digit:]].[[:digit:]].[[:digit:]]/    version: ${{ needs.generate-semantic-version.outputs.next-version }}/g" airbyte/Chart.yaml
          sed -i -E 's/version: [0-9]+\.[0-9]+\.[0-9]+/version: ${{ needs.generate-semantic-version.outputs.next-version }}/' airbyte/Chart.yaml

      - name: "Helm package"
        shell: bash
        run: |
          declare -a StringArray=("airbyte-bootloader" "airbyte-server" "airbyte-temporal" "airbyte-webapp" "airbyte-pod-sweeper" "airbyte-worker" "airbyte-metrics")
          for val in ${StringArray[@]}; do
            cd ./charts/${val} && helm dep update && cd $GITHUB_WORKSPACE
            sed -i -E  's/version: \"[0-9]+\.[0-9]+\.[0-9]+\"/version: \"${{ needs.generate-semantic-version.outputs.next-version }}\"/' ./charts/${val}/Chart.yaml
            helm package ./charts/${val} -d ./.github/airbyte-oss  --version ${{ needs.generate-semantic-version.outputs.next-version }}
          done
          helm repo index ./.github/airbyte-oss/
      
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Bump release to ${{ needs.generate-semantic-version.outputs.next-version }}'
          add: '.'
          cwd: './.github/airbyte-oss/'

      - name: "Helm package main chart"
        shell: bash
        run: |
          echo "Waiting for published charts to be synced in helm-charts repo"
          sleep 300
          declare -a StringArray=("airbyte")
          for val in ${StringArray[@]}; do
            cd ./charts/${val} && cat Chart.yaml && helm dep update && cd $GITHUB_WORKSPACE
            helm package ./charts/${val} -d ./.github/airbyte-oss  --version ${{ needs.generate-semantic-version.outputs.next-version }}
          done
          helm repo index ./.github/airbyte-oss/

      - name: Test
        shell: bash
        run: git status && sleep 120

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Bump release to ${{ needs.generate-semantic-version.outputs.next-version }}'
          add: '.'
          cwd: './.github/airbyte-oss/'
      
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Bump release to ${{ needs.generate-semantic-version.outputs.tag }}'
          add: '.'
          tag: ${{ needs.generate-semantic-version.outputs.tag }}
          

      
